#!/usr/bin/env bash
# Write docker-compose.yml for exactly three stacks: org1, org2, org3 (API + web each).
# Port pairs (<api_port> <web_port>) per row are the only customizable fields in fabric-hosts.def.
#
# fabric-hosts.def format — three data rows only (see repo file header):
#   HOST_KEY  MSP_ID  CRYPTO_PEER_DIR  GATEWAY_PEER  HOST_PEER_PORT  API_PORT  WEB_PORT
#
# Env:
#   FABRIC_HOSTS_DEF  path to def file (default: repo-root/fabric-hosts.def)
#   HASHEDRO_HOME     repo root (default: parent of scripts/)

set -euo pipefail

ROOT="${HASHEDRO_HOME:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
DEF="${FABRIC_HOSTS_DEF:-$ROOT/fabric-hosts.def}"
OUT="${ROOT}/docker-compose.yml"

if [[ ! -f "$DEF" ]]; then
  echo "Missing $DEF" >&2
  exit 1
fi

# shellcheck source=/dev/null
. "$(dirname "${BASH_SOURCE[0]}")/lib-fabric-hosts.sh"
fabric_hosts_validate_three "$DEF" || exit 1

DEF_DISPLAY="$DEF"
if [[ "$DEF" == "$ROOT"/* ]]; then
  DEF_DISPLAY="${DEF#"$ROOT"/}"
fi

{
  echo "# Generated by scripts/gen-docker-compose-hosts.sh — do not edit; change API/WEB ports in fabric-hosts.def and run make compose-gen."
  echo "# Source: $DEF_DISPLAY"
  echo "services:"
} >"$OUT"

while IFS= read -r raw || [[ -n "$raw" ]]; do
  line="${raw%%#*}"
  line="${line#"${line%%[![:space:]]*}"}"
  line="${line%"${line##*[![:space:]]}"}"
  [[ -z "$line" ]] && continue

  read -r key msp crypto_dir gateway_peer host_port api_port web_port <<<"$line"
  user_dir="User1@${crypto_dir}"

  cat >>"$OUT" <<EOF
  api-${key}:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: hashedroute-api:local
    ports:
      - "${api_port}:8080"
    environment:
      HTTP_ADDR: ":8080"
      FABRIC_CRYPTO_PATH: /fabric/crypto
      FABRIC_KEY_DIR: /fabric/crypto/users/${user_dir}/msp/keystore
      FABRIC_TLS_CA: /fabric/crypto/peers/${gateway_peer}/tls/ca.crt
      FABRIC_PEER_ENDPOINT: dns:///host.docker.internal:${host_port}
      FABRIC_GATEWAY_PEER: ${gateway_peer}
      FABRIC_MSP_ID: ${msp}
      FABRIC_CHANNEL: mychannel
      FABRIC_CHAINCODE: delivery
      FABRIC_CONTRACT_NAME: DeliveryContract
    volumes:
      - type: bind
        source: \${FABRIC_SAMPLES_ROOT}/test-network/organizations/peerOrganizations/${crypto_dir}
        target: /fabric/crypto
        read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  web-${key}:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: hashedroute-web:local
    ports:
      - "${web_port}:80"
    environment:
      NGINX_API_UPSTREAM: api-${key}
    depends_on:
      - api-${key}
    restart: unless-stopped
EOF
done <"$DEF"

echo "Wrote $OUT (three API + three web services)"
