#!/usr/bin/env bash
# Read fabric-hosts.def and write docker-compose.hosts.yml (API + web pairs).
# Default chaincode endorsement OR(...,.peer) uses the same MSP_ID column; see scripts/lib-fabric-hosts.sh.
#
# fabric-hosts.def format (whitespace-separated, one stack per line):
#   HOST_KEY  MSP_ID  CRYPTO_PEER_DIR  GATEWAY_PEER  HOST_PEER_PORT  API_PORT  WEB_PORT
# HOST_KEY must be unique (Docker Compose service names api-<KEY> / web-<KEY>).
# Example:
#   org1 Org1MSP org1.example.com peer0.org1.example.com 7051 8080 8081
#
# CRYPTO_PEER_DIR is the folder under .../peerOrganizations/ (bind-mounted read-only).
# Enrolled user is assumed User1@${CRYPTO_PEER_DIR} (matches fabric-samples test-network).
#
# Env:
#   FABRIC_HOSTS_DEF  path to def file (default: repo-root/fabric-hosts.def)
#   HASHEDRO_HOME     repo root (default: parent of scripts/)

set -euo pipefail

ROOT="${HASHEDRO_HOME:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
DEF="${FABRIC_HOSTS_DEF:-$ROOT/fabric-hosts.def}"
OUT="${ROOT}/docker-compose.hosts.yml"

if [[ ! -f "$DEF" ]]; then
  echo "Missing $DEF — copy fabric-hosts.def.example or create fabric-hosts.def" >&2
  exit 1
fi

{
  echo "# Generated by scripts/gen-docker-compose-hosts.sh — do not edit by hand."
  echo "# Source: $DEF"
  echo "services:"
} >"$OUT"

seen_keys=()
while IFS= read -r raw || [[ -n "$raw" ]]; do
  line="${raw%%#*}"
  line="${line#"${line%%[![:space:]]*}"}"
  line="${line%"${line##*[![:space:]]}"}"
  [[ -z "$line" ]] && continue

  read -r key msp crypto_dir gateway_peer host_port api_port web_port <<<"$line"
  if [[ -z "${key:-}" || -z "${msp:-}" || -z "${crypto_dir:-}" || -z "${gateway_peer:-}" || -z "${host_port:-}" || -z "${api_port:-}" || -z "${web_port:-}" ]]; then
    echo "Invalid line in $DEF (need 7 fields): $raw" >&2
    exit 1
  fi
  if ! [[ "$key" =~ ^[a-zA-Z0-9][a-zA-Z0-9.-]*$ ]]; then
    echo "Invalid HOST_KEY (use letters, digits, dots, hyphens): $key" >&2
    exit 1
  fi

  dup=0
  if ((${#seen_keys[@]})); then
    for sk in "${seen_keys[@]}"; do
      if [[ "$sk" == "$key" ]]; then
        dup=1
        break
      fi
    done
  fi
  if [[ "$dup" -ne 0 ]]; then
    echo "Duplicate HOST_KEY '$key' in $DEF — each line needs a unique first column (e.g. org2 and org3, not two 'org2')." >&2
    echo "  Offending line: $line" >&2
    exit 1
  fi
  seen_keys+=("$key")

  user_dir="User1@${crypto_dir}"

  cat >>"$OUT" <<EOF
  api-${key}:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: hashedroute-api:local
    ports:
      - "${api_port}:8080"
    environment:
      HTTP_ADDR: ":8080"
      FABRIC_CRYPTO_PATH: /fabric/crypto
      FABRIC_KEY_DIR: /fabric/crypto/users/${user_dir}/msp/keystore
      FABRIC_TLS_CA: /fabric/crypto/peers/${gateway_peer}/tls/ca.crt
      FABRIC_PEER_ENDPOINT: dns:///host.docker.internal:${host_port}
      FABRIC_GATEWAY_PEER: ${gateway_peer}
      FABRIC_MSP_ID: ${msp}
      FABRIC_CHANNEL: mychannel
      FABRIC_CHAINCODE: delivery
      FABRIC_CONTRACT_NAME: DeliveryContract
    volumes:
      - type: bind
        source: \${FABRIC_SAMPLES_ROOT}/test-network/organizations/peerOrganizations/${crypto_dir}
        target: /fabric/crypto
        read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  web-${key}:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: hashedroute-web:local
    ports:
      - "${web_port}:80"
    environment:
      NGINX_API_UPSTREAM: api-${key}
    depends_on:
      - api-${key}
    restart: unless-stopped
EOF
done <"$DEF"

echo "Wrote $OUT ($(grep -c '^  api-' "$OUT" || true) API / web pairs)"
